language: node_js
node_js:
  - '10'
script:
  - yarn lint
  - yarn build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_PAGES_TOKEN
    fqdn: peterhegman.com
    target_branch: master
    keep_history: true
    on:
      tags: true