language: node_js
node_js:
  - '10'
script:
  - yarn test:unit
  - yarn lint
  - yarn build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_PAGES_TOKEN
    local_dir: dist
    fqdn: peterhegman.com
    on:
      branch: master
      tags: true
